# Generated by Django 3.1 on 2020-11-01 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('task_password', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=50)),
                ('user_task', models.ManyToManyField(blank=True, to='task.Task')),
            ],
        ),
    ]
