# Generated by Django 3.1 on 2020-11-28 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='reply',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task.messages'),
        ),
    ]
