# Generated by Django 3.1.2 on 2020-10-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201021_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_task',
            field=models.ManyToManyField(blank=True, to='task.Task'),
        ),
    ]
